version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bitcoin-golang"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-p9jdeioivm7v"
s3_prefix = "bitcoin-golang"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
